### ISSUE TITLE
iOS 16 / tvOS 16 compatibility

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#212]
As usual we must work on compatibility updates for iOS 16 and tvOS 16.

**Comment by defagos** [comment]
The first major issue we face is with tvOS 16. Cells embedded in SwiftUI and made of a top-level button with the card button style namely break. I reported this issue to Apple as FB10576560 and I implemented a workaround using a custom cell style (we lose usual tvOS image tilting behavior but at least nothing is broken anymore).

**Comment by defagos** [comment]
Apple reworked some rotation APIs (this probably occurs every two or three years and becomes a bit annoying):

- We cannot set the device orientation anymore, this does not work any logs a warning to the console at runtime. Instead, beta 2 introruced a [new API](https://developer.apple.com/documentation/uikit/uiwindowscene/3975944-requestgeometryupdate/) which seems to work.
- If supported interface orientations change over the lifetime of a view controller for some reason there is a new API `setNeedsUpdateOfSupportedInterfaceOrientations()` which can be called to force a refresh. The documentation states that changes should be animated but this is not the case at the moment but my attempt with a simple project (a button changing the list of supported orientations and calling this API) shows that no animation has been implemented yet.

With the new rotation API we can implement the iPhone full-screen button behavior again. Still I found two main issues with rotation behavior on iOS 16 which I suspect to be bugs:

- Open the player, rotate to landscape and dismiss. After a short while the interface is forced to portrait, but unlike what we had on iOS 15 no animation occurs. I guess this is related to the issue described above.
- Open the player, rotate to landscape and open the settings window. After a short while the user interface is forced to portrait without animation. It appears that UIKit triggers an internal orientation update which asks view controllers below (tab bar controller, which should be ignored because the player modal covers the screen entirely). I suspect this is also a bug of this new API, maybe called too agressively and on the wrong controller.

We should report these issues to Apple but rotation is too tricky to fix for the moment. We don't know yet how rotation changes will evolve in further betas (currently beta 3), so we should wait and not write workarounds which themselves might break in a near future.

**Comment by defagos** [comment]
Two naive workarounds we could keep in mind but which we should only apply if these issues persist in the RC:

- The animation can be restored by calling `[UIDevice.currentDevice rotateToUserInterfaceOrientation:]` on view controller dismissal with a 0.1 delay. Ugly.
- Container view controllers can check if there is a presented view controller and return the presented view controller supported orientation if this is the case. Might be risky though.

**Comment by defagos** [comment]
The second issue above appears if the _intermediate_ view (here the player) is presented with a custom modal presentation style. No issue arises with the full screen presentation style.

**Comment by pyby** [comment]
On developer tools, Xcode previews build fails because of a binary static dependency.

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060004a5a4090):'GoogleCastSDK-ios-no-bluetooth'>)
```

Other developers have the same issue with Xcode 14 beta 2 and 3. An Apple engineer is aware of.
https://developer.apple.com/forums/thread/707569

**Comment by defagos** [comment]
There is a [new API to copy text from videos](https://developer.apple.com/videos/play/wwdc2022/10147) which has a possible performance overhead, but it is only available on `AVPlayerViewController` for iOS at the moment. So nothing to disable in Letterbox.

**Comment by defagos** [comment]
> On developer tools, Xcode previews build fails because of a binary static dependency.
> 
> ```
> HumanReadableSwiftError
> 
> SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060004a5a4090):'GoogleCastSDK-ios-no-bluetooth'>)
> ```
> 
> Other developers have the same issue with Xcode 14 beta 2 and 3. An Apple engineer is aware of. https://developer.apple.com/forums/thread/707569

Fixed in beta 4

**Comment by defagos** [comment]
Not fixed in beta 4.

**Comment by defagos** [comment]
There are selection issues on tvOS. For example sometimes clicking on topics does not do anything. This is something that needs to be tested in further betas (especially if the card button style is fixed and can be restored) and fixed if needed.

**Comment by pyby** [comment]
The card button style on tvOS issue is not fixed in beta 5.

**Comment by pyby** [comment]
Xcode 14 RC update:
- The card button style on tvOS issue is not fixed. The build keeps the custom style.
- Xcode SwiftUI previews build fails. The error occurred with `AppCenterCrashes` product and `GoogleCastSDK-ios-no-bluetooth` product.

With AppcenterCrashes example, a [radar](http://openradar.appspot.com/radar?id=5579116359188480) is opened.

**Comment by pyby** [comment]
In CarPlay player, the `CPNowPlayingImageButton` displaying a tiny speedometer icon, from the SF Symbol font.
It looks like a regression with SDK 16.0.

Using `SymbolConfiguration` does not change the icon size.

For now, I transformed it as an image.

**Comment by pyby** [comment]
We should reopen the issue or create new related issue with non closed topics.
